### ISSUE TITLE
Discord id

### ISSUE THREAD

**Issue by iRxngo** [kimoVoid/BetaQOL#1]
btw can i have you discord ? (not for this project)

**Comment by kimoVoid** [comment]
What for?

**Comment by iRxngo** [comment]
nvm

**Comment by iRxngo** [comment]
Actually i want it for your bw quest plugin

**Comment by kimoVoid** [comment]
Sorry but this project has nothing to do with that, and I quit making bw related plugins in 2021.

**Comment by iRxngo** [comment]
Bro pls i need the src

**Comment by iRxngo** [comment]
I spent a lot of time to find you
